inherit_from: model_versions/v0_initial/configs/train.yaml

data:
  path: /dataset

training:
  out_dir: out/scratch/v0_weights_with_duff_basis

test:
  model_file: /workspace/model_versions/v0_initial/weights/model_best.pt

generation:
  vis_n_outputs: 1
  generate_pointcloud: false
  copy_groundtruth: false
  copy_input: true

profiling:
  one_sample_per_category: true
