inherit_from: model_versions/v0_initial/configs/train.yaml

data:
  path: /dataset

training:
  out_dir: out/v0_initial/test

test:
  model_file: /workspace/model_versions/v0_initial/weights/model_best.pt

generation:
  vis_n_outputs: null
  generate_pointcloud: false
  copy_groundtruth: false
  copy_input: false
