inherit_from: configs/shapenet/v1_duff/train.yaml

data:
  path: /dataset

training:
  out_dir: out/v1_duff/test

test:
  model_file: /workspace/out/v1_duff/train/model_best.pt

generation:
  vis_n_outputs: null
  generate_pointcloud: false
  copy_groundtruth: false
  copy_input: false
