inherit_from: configs/shapenet/v2_patch_tokens/train.yaml

data:
  path: /dataset

training:
  out_dir: out/v2_patch_tokens/profile

test:
  model_file: /workspace/out/v2_patch_tokens/train/model_best.pt

generation:
  vis_n_outputs: 1
  generate_pointcloud: false
  copy_groundtruth: false
  copy_input: true

profiling:
  one_sample_per_category: true
